import Head from "next/head";
import { Footer } from "@/components/footer";
import Navbar from "@/components/navbar";
import { Disclosure } from "@headlessui/react";
export default function Aboutus() {
  return (
    <>
      <Navbar />
      <Head>
        <title>Frequently Asked Questions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <div className="2xl:container 2xl:mx-auto lg:py-16 lg:px-20 md:py-12 md:px-6 py-9 px-4 min-h-screen">
          <div className="flex flex-col lg:flex-row justify-between gap-8">
            <div className="w-full lg:w-8/12">
              <img className="w-full h-full" src="/faq.jpg" alt="faq" />
            </div>
            <div className="px-6 content-center w-full max-w-md p-2 mx-auto bg-white rounded-2xl">
              <h2 className="text-2xl font-semibold text-black">
                Frequently Asked Questions
              </h2>
              <p className="mt-4 mb-8 text-gray-600">
                Pertanyaan yang mungkin cukup dalam membantu anda.
              </p>
              <Disclosure>
                {({ open }) => (
                  <>
                    <Disclosure.Button className="flex justify-between w-full px-4 py-2 text-l font-medium text-left text-purple-900 bg-purple-100 rounded-lg hover:bg-purple-200 focus:outline-none focus-visible:ring focus-visible:ring-purple-500 focus-visible:ring-opacity-75">
                      <span>
                        Apa itu sistem informasi tempat parkir berbasis web
                        dengan info detail realtime lahan parkirnya?
                      </span>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        className={`${
                          open ? "rotate-180 transform" : ""
                        } h-5 w-5 text-purple-500`}
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                        />
                      </svg>
                    </Disclosure.Button>
                    <Disclosure.Panel className="px-4 pt-4 pb-2 text-sm text-gray-500">
                      Sistem informasi tempat parkir berbasis web dengan info
                      detail realtime lahan parkirnya adalah sebuah sistem
                      informasi yang memungkinkan pengguna untuk mengetahui
                      informasi detail mengenai lokasi parkir yang tersedia
                      secara realtime di suatu lokasi tertentu.
                    </Disclosure.Panel>
                  </>
                )}
              </Disclosure>
              <Disclosure as="div" className="mt-2">
                {({ open }) => (
                  <>
                    <Disclosure.Button className="flex justify-between w-full px-4 py-2 text-l font-medium text-left text-purple-900 bg-purple-100 rounded-lg hover:bg-purple-200 focus:outline-none focus-visible:ring focus-visible:ring-purple-500 focus-visible:ring-opacity-75">
                      <span>
                        Apakah sistem informasi tempat parkir berbasis web
                        dengan info detail realtime lahan parkirnya dapat
                        diakses dari semua jenis perangkat?
                      </span>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        className={`${
                          open ? "rotate-180 transform" : ""
                        } h-5 w-5 text-purple-500`}
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                        />
                      </svg>
                    </Disclosure.Button>
                    <Disclosure.Panel className="px-4 pt-4 pb-2 text-sm text-gray-500">
                      Maaf, untuk saat ini sistem hanya dapat diakses dari jenis
                      perangkat dengan koneksi internet, seperti laptop dan
                      komputer. Untuk pengembangan perangkat smartphone masih
                      dalam tahap pengembangan
                    </Disclosure.Panel>
                  </>
                )}
              </Disclosure>
              <Disclosure as="div" className="mt-2">
                {({ open }) => (
                  <>
                    <Disclosure.Button className="flex justify-between w-full px-4 py-2 text-l font-medium text-left text-purple-900 bg-purple-100 rounded-lg hover:bg-purple-200 focus:outline-none focus-visible:ring focus-visible:ring-purple-500 focus-visible:ring-opacity-75">
                      <span>
                        Apakah informasi yang ditampilkan oleh sistem informasi
                        tempat parkir berbasis web dengan info detail realtime
                        lahan parkirnya selalu akurat?
                      </span>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        strokeWidth={1.5}
                        stroke="currentColor"
                        className={`${
                          open ? "rotate-180 transform" : ""
                        } h-5 w-5 text-purple-500`}
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M19.5 8.25l-7.5 7.5-7.5-7.5"
                        />
                      </svg>
                    </Disclosure.Button>
                    <Disclosure.Panel className="px-4 pt-4 pb-2 text-sm text-gray-500">
                      Informasi yang ditampilkan oleh sistem ini didapatkan
                      secara realtime, sehingga tingkat akurasinya sangat
                      tinggi. Namun, informasi ini dapat berubah sewaktu-waktu
                      tergantung pada jumlah kendaraan yang memasuki dan
                      meninggalkan lokasi parkir.
                    </Disclosure.Panel>
                  </>
                )}
              </Disclosure>
            </div>
          </div>
          <div className="w-full px-4 pt-16"></div>
        </div>
      </main>
      <Footer />
    </>
  );
}
