import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import { Footer } from '@/components/footer';
import Link from 'next/link';
import Navbar from '@/components/navbar';

export default function Aboutus() {
  return (
    <>
      <Navbar />
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white min-h-screen">
        <div className="flex py-5 justify-center  text-black">
          <div className=" w-4/5 px-5 bg-white drop-shadow-2xl rounded-lg">
            <div className="flex justify-center py-5">
              <h1 className="text-2xl font-bold">Histori Parkiran</h1>
            </div>

            <div className="flex flex-col">
              <div className="overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div className="inline-block min-w-full py-2 sm:px-6 lg:px-8">
                  <div className="overflow-hidden">
                    <table className="min-w-full text-left">
                      <thead className="border-b font-medium border-black">
                        <tr>
                          <th scope="col" className="px-6 py-4">
                            #
                          </th>
                          <th scope="col" className="px-6 py-4">
                            Nama Parkiran
                          </th>
                          <th scope="col" className="px-6 py-4">
                            Start
                          </th>
                          <th scope="col" className="px-6 py-4">
                            End
                          </th>
                          <th scope="col" className="px-6 py-4">
                            Status
                          </th>
                          <th scope="col" className=" px-6 py-4">
                            Confirmation
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr className="border-b dark:border-neutral-500">
                          <td className="whitespace-nowrap px-6 py-4 font-medium">1</td>
                          <td className="whitespace-nowrap px-6 py-4">Parkiran Biru FIS</td>
                          <td className="whitespace-nowrap px-6 py-4">13.00 27/30/22</td>
                          <td className="whitespace-nowrap px-6 py-4">3.00 27/30/22</td>
                          <td className="whitespace-nowrap px-6 py-4">Aktif</td>
                          <td className="whitespace-nowrap px-6 py-4">
                            <button className="bg-yellow-500 px-3 py-3 rounded-full text-white">
                              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                              </svg>
                            </button>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
