import { GetServerSidePropsContext } from "next";
import { getSession, useSession } from "next-auth/react";
import { Head } from "next/document";

export default function Redirect() {
    
    return (
        <>
            <Head>
                <title>Redirecting...</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </>
    )
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
    const session = await getSession(context)
    const role = session?.user?.role

    let redirectUrl = ""

    if (role === "admin") {
        redirectUrl = "/admin/add-park"
    }

    else if (role === "operator") {
        redirectUrl = "/operators/dashboard"
    }

    else if (role === "user") {
        redirectUrl = "/home"
    }

    else {
        redirectUrl = "/login"
    }

    return {
        redirect: {
            destination: redirectUrl,
            permanent: false
        }
    }

}