import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/navbar';
import { Footer } from '@/components/footer';
import { Rating } from '@/components/userRatings';
import dynamic from 'next/dynamic';
import { Chart } from 'chart.js';
const inter = Inter({ subsets: ['latin'] });
const Maps = dynamic(() => import('@/components/map'), {
  ssr: false,
});

export default function ParkingDetails() {
  return (
    // Front End Parking Rate and Review
    <>
      <Head>
        <title>Detail Parkir</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="min-h-screen bg-white">
        <div className="lg:flex px-10 py-10">
          <div className="container rounded-xl pb-2">
            <Maps />
          </div>
          <div className="container lg:pl-10">
            <div className=" py-2 px-2 lg:px-5 rounded-xl bg-gray-300">
              <div className=" flex justify-center text-4xl font-bold text-black">
                <h1>PARKIRAN KUNING</h1>
              </div>
              <div className="py-2">
                <div className="flex items-center mb-3">
                  <svg aria-hidden="true" className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <title>First star</title>
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                  </svg>
                  <svg aria-hidden="true" className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <title>Second star</title>
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                  </svg>
                  <svg aria-hidden="true" className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <title>Third star</title>
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                  </svg>
                  <svg aria-hidden="true" className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <title>Fourth star</title>
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                  </svg>
                  <svg aria-hidden="true" className="w-5 h-5 text-gray-300 dark:text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <title>Fifth star</title>
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
                  </svg>
                  <p className="ml-2 text-sm font-medium text-gray-900 dark:text-white">4.95 out of 5</p>
                </div>
                <p className="text-sm font-medium text-gray-500 dark:text-gray-400">1,745 global ratings</p>
                <div className="flex items-center mt-4">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">5 star</span>
                  <div className="w-2/4 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
                    <div className="h-5 bg-yellow-400 rounded" style={{}}></div>
                  </div>
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">70%</span>
                </div>
                <div className="flex items-center mt-4">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">4 star</span>
                  <div className="w-2/4 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
                    <div className="h-5 bg-yellow-400 rounded" style={{}}></div>
                  </div>
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">17%</span>
                </div>
                <div className="flex items-center mt-4">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">3 star</span>
                  <div className="w-2/4 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
                    <div className="h-5 bg-yellow-400 rounded" style={{}}></div>
                  </div>
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">8%</span>
                </div>
                <div className="flex items-center mt-4">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">2 star</span>
                  <div className="w-2/4 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
                    <div className="h-5 bg-yellow-400 rounded" style={{}}></div>
                  </div>
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">4%</span>
                </div>
                <div className="flex items-center mt-4">
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">1 star</span>
                  <div className="w-2/4 h-5 mx-4 bg-gray-200 rounded dark:bg-gray-700">
                    <div className="h-5 bg-yellow-400 rounded" style={{}}></div>
                  </div>
                  <span className="text-sm font-medium text-blue-600 dark:text-blue-500">1%</span>
                </div>
              </div>
              <div>
                <Komentar />
                <Komentar />
              </div>
              <div className="flex justify-between">
                <div className="flex items-center rounded-full bg-blue-700 py-2 px-5">
                  <img src="/star.svg" alt="" />
                  <p className="text-xl">5</p>
                </div>
                <div className="flex items-center rounded-full text-xl bg-blue-700 py-2 px-5">
                  <a href="">BERI PENILAIAN</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}

export function Komentar() {
  return (
    <>
      <div className="pb-2">
        <div className="flex justify-between items-center text-black">
          <div className="w-10">
            <img src="/gambarprofile.svg" alt="" />
          </div>
          <div className="font-bold">
            <p>Nama Pengguna</p>
          </div>
          <div className="flex">
            <Rating />
          </div>
        </div>
        <div className="text-black">
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Error debitis corrupti laboriosam laborum sit magnam? Quis hic voluptatem, impedit, neque fuga maiores quae placeat ducimus vitae, beatae dolores aperiam quos.</p>
        </div>
      </div>
    </>
  );
}

export function Chartbar() {
  return (
    <div>
      <p>tes bar</p>
    </div>
  );
}
