import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar  from '@/components/navbar';
import { Footer } from '@/components/footer';
import { Rating } from '@/components/userRatings';
import dynamic from 'next/dynamic';
const Maps = dynamic(() => import('@/components/map'), {
  ssr: false,
});

const inter = Inter({ subsets: ['latin'] });

export default function ParkingRate() {
  return (
    <>
      <Head>
        <title>Rating Parkir</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main className="min-h-screen bg-white">
        <div className="lg:flex px-10 py-10">
          <div className="container rounded-xl pb-2">
            <Maps />
          </div>
          <div className="container lg:pl-10">
            <div className=" py-5 px-5 rounded-xl bg-gray-300">
              <div className=" lg:flex justify-center text-4xl font-bold text-black">
                <h1>PARKIRAN KUNING</h1>
              </div>
              <div className="flex justify-center py-5">
                <Rating />
              </div>
              <div className="flex justify-center text-black font-bold">
                <p>BAGAIMANA MENURUTMU KAMU?</p>
              </div>
              <div className="flex justify-center text-black py-2">
                <textarea name="" id="" className="w-96 h-36"></textarea>
              </div>
              <div className="flex justify-center pt-5">
                <div className="flex items-center rounded-full text-xl bg-blue-700 py-2 px-5">
                  <a href="">BERI PENILAIAN</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
