import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

export default function Profile() {
  // Front End User Profile
  return (
    <>
      <Head>
        <title>Profil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <div className=" bg-blue-800">
            <div className="flex text-5xl py-5 px-5">
              <div className="px-5">
                <h1>Profil</h1>
              </div>
            </div>
            <div className="flex md:text-5xl text-3xl md:px-24 px-5 pb-5 items-center">
              <div>
                <img src="/gambarprofile.png" alt="" width={100} />
              </div>
              <div className="px-5 font-bold">
                <h3>@nama</h3>
              </div>
              <div>
                <button>
                  <img src="/kamera.png" alt="" width={50} />
                </button>
              </div>
            </div>
          </div>
          <div className=" bg-white min-h-screen pt-10 lg:px-64 md:px-24 sm:px-1 text-blue-800">
            <div className="flex text-center justify-center text-5xl font-bold pb-10">
              <img src="/gambarubah.png" alt="" width={50} />
              <h3 className="pl-5">
                <a href="">Ubah</a>
              </h3>
            </div>
            <div className="flex justify-between rounded-lg bg-gray-200 font-bold items-center py-2 px-2 text-3xl">
              <p>Password</p>
              <p>*****</p>
            </div>
            <div className="flex justify-center py-20">
              <button className="bg-blue-800 text-white text-3xl px-10 py-1 rounded-full">LOGOUT</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
