import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

export default function Profile() {
  // Front End User Profile
  return (
    <>
      <Head>
        <title>Profil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div>
          <div className="text-center">
            <button>UBAH</button>
          </div>
        </div>
      </div>
    </>
  );
}
